// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  Admin_Tools = "Admin Tools",
  Balloons = "Balloons",
  Banner = "Banner",
  BannerText = "BannerText",
  BannerText_2 = "BannerText_2",
  Batch_toggle = "Batch toggle",
  Cameras = "Cameras",
  Effects = "Effects",
  Fixed_View_Camera = "Fixed View Camera",
  Light_Ref = "Light Ref",
  Lights_Back = "Lights Back",
  Lights_Bottom = "Lights Bottom",
  Lights_Top = "Lights Top",
  Red_Button_2 = "Red Button_2",
  Snow = "Snow",
  Trigger_Area = "Trigger Area",
  Trigger1 = "Trigger1",
  Trigger2 = "Trigger2",
  Trigger3 = "Trigger3",
  Trigger4 = "Trigger4",
  Utils = "Utils",
  VCameraRef = "VCameraRef",
  VCameraRef2 = "VCameraRef2",
  VCameraRef3 = "VCameraRef3",
  VCameraRef4 = "VCameraRef4",
  VCameraRef5 = "VCameraRef5",
  VCameraRef6 = "VCameraRef6",
  VCameraRef7 = "VCameraRef7",
  VCameraRef8 = "VCameraRef8",
  Video_Screen = "Video Screen",
  Voting = "Voting",
  VotingDoor1 = "VotingDoor1",
  VotingDoor2 = "VotingDoor2",
  VotingDoor3 = "VotingDoor3",
  VotingDoor4 = "VotingDoor4",
  VotingZone1 = "VotingZone1",
  VotingZone2 = "VotingZone2",
  VotingZone3 = "VotingZone3",
  VotingZone4 = "VotingZone4",
  base = "base",
  cameraToggle = "cameraToggle",
  confettiControl = "confettiControl",
  confetti_3 = "confetti_3",
  confetti_3_4 = "confetti_3_4",
  confetti_3_5 = "confetti_3_5",
  confetti_3_5_6 = "confetti_3_5_6",
  confetti_3_5_6_7 = "confetti_3_5_6_7",
  confetti_4 = "confetti_4",
  confetti_4_5 = "confetti_4_5",
  confetti_4_6 = "confetti_4_6",
  confetti_4_6_7 = "confetti_4_6_7",
  confetti_4_6_7_8 = "confetti_4_6_7_8",
  confetti_Blue = "confetti_Blue",
  confetti_Blue_2 = "confetti_Blue_2",
  confetti_Blue_3 = "confetti_Blue_3",
  confetti_Blue_4 = "confetti_Blue_4",
  confetti_Blue_5 = "confetti_Blue_5",
  confetti_Pink = "confetti_Pink",
  confetti_Pink_2 = "confetti_Pink_2",
  confetti_Pink_3 = "confetti_Pink_3",
  confetti_Pink_4 = "confetti_Pink_4",
  confetti_Pink_5 = "confetti_Pink_5",
  emoteToggle = "emoteToggle",
  firework = "firework",
  fireworkControl = "fireworkControl",
  firework_2 = "firework_2",
  firework_3 = "firework_3",
  firework_4 = "firework_4",
  mallorca = "mallorca",
  pedestalControl = "pedestalControl",
  scheduleController = "scheduleController",
  slideSound = "slideSound",
} 
