// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  Admin_Tools = "Admin Tools",
  Archway_of_Kindness = "Archway of Kindness",
  Banner = "Banner",
  BannerText = "BannerText",
  Batch_toggle = "Batch toggle",
  Cameras = "Cameras",
  Effects = "Effects",
  Light_Ref = "Light Ref",
  LightRef = "LightRef",
  Lights_Back = "Lights Back",
  Lights_Bottom = "Lights Bottom",
  Lights_Top = "Lights Top",
  Needle = "Needle",
  Snow = "Snow",
  Trigger_Area = "Trigger Area",
  Utils = "Utils",
  VCameraRef = "VCameraRef",
  VCameraRef2 = "VCameraRef2",
  VCameraRef3 = "VCameraRef3",
  VCameraRef4 = "VCameraRef4",
  VCameraRef5 = "VCameraRef5",
  VCameraRef6 = "VCameraRef6",
  VCameraRef7 = "VCameraRef7",
  VCameraRef8 = "VCameraRef8",
  base = "base",
  button = "button",
  cameraToggle = "cameraToggle",
  clapMeter = "clapMeter",
  confetti = "confetti",
  confettiControl = "confettiControl",
  confetti_2 = "confetti_2",
  confetti_3 = "confetti_3",
  confetti_3_4 = "confetti_3_4",
  confetti_3_5 = "confetti_3_5",
  confetti_3_5_6 = "confetti_3_5_6",
  confetti_3_5_6_7 = "confetti_3_5_6_7",
  confetti_4 = "confetti_4",
  confetti_4_5 = "confetti_4_5",
  confetti_4_6 = "confetti_4_6",
  confetti_4_6_7 = "confetti_4_6_7",
  confetti_4_6_7_8 = "confetti_4_6_7_8",
  emoteToggle = "emoteToggle",
  firework = "firework",
  fireworkControl = "fireworkControl",
  firework_2 = "firework_2",
  firework_3 = "firework_3",
  firework_4 = "firework_4",
  lightsToggle = "lightsToggle",
  pedestal = "pedestal",
  pedestalControl = "pedestalControl",
  pedestal_old = "pedestal_old",
  screen = "screen",
  spiral = "spiral",
} 
